name: Generate and Deploy DBT Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Generate and Deploy DBT Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Generate DBT docs
        run: |
          source .venv/bin/activate
          dbt docs generate
        env: 
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      - name: Prepare docs for upload
        run: |
          cd target
          mkdir -p ${{ github.workspace }}/docs
          cp *.json *.html graph.gpickle ${{ github.workspace }}/docs
          ls -ltra ${{ github.workspace }}/docs

      - name: Check for symlinks and hard links
        run: |
          if find ${{ github.workspace }}/docs -type l | read; then
            echo "Error: Symlinks found in the docs directory."
            exit 1
          fi
          if find ${{ github.workspace }}/docs -type f -links +1 | read; then
            echo "Error: Hard links found in the docs directory."
            exit 1
          fi
      
      - name: set permissions
        run: |
          chmod -R 755 ${{ github.workspace }}/docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/docs
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages